export const PASSWORD = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 128,
};

const NAMESPACE = "auth";
const FIELDS = "common.fields";
const CODE_KEY = "code";
const EMAIL_KEY = "email";
const PASSWORD_KEY = "password";
const PASSWORD_CONFIRM_KEY = "password_confirmation";
const ERROR_KEY = "validation_messages";

export const FIELD_TYPES = {
  LABEL: "label",
  PLACEHOLDER: "placeholder",
};

export const ERROR_TYPES = {
  REQUIRED: "required",
  MIN_LENGTH: "min-length",
  MAX_LENGTH: "max-length",
  MATCH: "match",
  INVALID: "invalid",
};

export const CODE_FIELD = {
  name: CODE_KEY,
  label: `${NAMESPACE}:${FIELDS}.${CODE_KEY}.${FIELD_TYPES.LABEL}`,
  placeholder: `${NAMESPACE}:${FIELDS}.${CODE_KEY}.${FIELD_TYPES.PLACEHOLDER}`,
  error: {
    [ERROR_TYPES.REQUIRED]: `${NAMESPACE}:${FIELDS}.${CODE_KEY}.${ERROR_KEY}.${ERROR_TYPES.REQUIRED}`,
  },
};

export const EMAIL_FIELD = {
  name: EMAIL_KEY,
  label: `${NAMESPACE}:${FIELDS}.${EMAIL_KEY}.${FIELD_TYPES.LABEL}`,
  placeholder: `${NAMESPACE}:${FIELDS}.${EMAIL_KEY}.${FIELD_TYPES.PLACEHOLDER}`,
  error: {
    [ERROR_TYPES.REQUIRED]: `${NAMESPACE}:${FIELDS}.${EMAIL_KEY}.${ERROR_KEY}.${ERROR_TYPES.REQUIRED}`,
    [ERROR_TYPES.INVALID]: `${NAMESPACE}:${FIELDS}.${EMAIL_KEY}.${ERROR_KEY}.${ERROR_TYPES.INVALID}`,
  },
};

export const PASSWORD_FIELD = {
  name: PASSWORD_KEY,
  label: `${NAMESPACE}:${FIELDS}.${PASSWORD_KEY}.${FIELD_TYPES.LABEL}`,
  placeholder: `${NAMESPACE}:${FIELDS}.${PASSWORD_KEY}.${FIELD_TYPES.PLACEHOLDER}`,
  error: {
    [ERROR_TYPES.REQUIRED]: `${NAMESPACE}:${FIELDS}.${PASSWORD_KEY}.${ERROR_KEY}.${ERROR_TYPES.REQUIRED}`,
    [ERROR_TYPES.MIN_LENGTH]: `${NAMESPACE}:${FIELDS}.${PASSWORD_KEY}.${ERROR_KEY}.${ERROR_TYPES.MIN_LENGTH}`,
    [ERROR_TYPES.MAX_LENGTH]: `${NAMESPACE}:${FIELDS}.${PASSWORD_KEY}.${ERROR_KEY}.${ERROR_TYPES.MAX_LENGTH}`,
  },
};

export const PASSWORD_CONFIRM_FIELD = {
  name: PASSWORD_CONFIRM_KEY,
  label: `${NAMESPACE}:${FIELDS}.${PASSWORD_CONFIRM_KEY}.${FIELD_TYPES.LABEL}`,
  placeholder: `${NAMESPACE}:${FIELDS}.${PASSWORD_CONFIRM_KEY}.${FIELD_TYPES.PLACEHOLDER}`,
  error: {
    [ERROR_TYPES.REQUIRED]: `${NAMESPACE}:${FIELDS}.${PASSWORD_CONFIRM_KEY}.${ERROR_KEY}.${ERROR_TYPES.REQUIRED}`,
    [ERROR_TYPES.MATCH]: `${NAMESPACE}:${FIELDS}.${PASSWORD_CONFIRM_KEY}.${ERROR_KEY}.${ERROR_TYPES.MATCH}`,
  },
};
